name: dawarich
services:
  dawarich_redis:
    image: redis:7.0-alpine
    network_mode: bridge
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/redis
        target: /data
    restart: always
    x-casaos:
      ports: []
      volumes:
        - container: /data
          description:
            en_us: Redis data directory
    container_name: dawarich_redis

  dawarich_db:
    image: postgres:14.2-alpine
    network_mode: bridge
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/db
        target: /var/lib/postgresql/data
      - type: bind
        source: /DATA/AppData/$AppID/shared
        target: /var/shared
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    x-casaos:
      ports: []
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: Postgres data directory
    container_name: dawarich_db

  dawarich_app:
    image: freikin/dawarich:0.13.0
    network_mode: bridge
    ports:
      - target: 3000
        published: ${WEBUI_PORT}
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/gem_cache
        target: /usr/local/bundle
      - type: bind
        source: /DATA/AppData/$AppID/public
        target: /var/app/public
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['bin/dev']
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: dawarich_development
      APPLICATION_HOST: ${APP_HOST}
      APPLICATION_PROTOCOL: ${APP_PROTOCOL}
      TIME_ZONE: $TZ
    restart: unless-stopped
    x-casaos:
      ports:
        - container: "3000"
          description:
            en_us: Web UI port for dawarich app
      volumes:
        - container: /usr/local/bundle
          description:
            en_us: Ruby gem cache
        - container: /var/app/public
          description:
            en_us: Public folder
    container_name: dawarich_app

  dawarich_sidekiq:
    image: freikin/dawarich:0.1.0
    network_mode: bridge
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/gem_cache
        target: /usr/local/bundle
      - type: bind
        source: /DATA/AppData/$AppID/public
        target: /var/app/public
    stdin_open: true
    tty: true
    entrypoint: dev-entrypoint.sh
    command: ['sidekiq']
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://dawarich_redis:6379/0
      DATABASE_HOST: dawarich_db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: dawarich_development
      APPLICATION_HOST: ${APP_HOST}
      APPLICATION_PROTOCOL: ${APP_PROTOCOL}
    restart: unless-stopped
    x-casaos:
      ports: []
      volumes:
        - container: /usr/local/bundle
          description:
            en_us: Ruby gem cache
        - container: /var/app/public
          description:
            en_us: Public folder
    container_name: dawarich_sidekiq

x-casaos:
  architectures:
    - amd64
    - arm64
  main: dawarich_app
  author: Freika
  category: Development
  description:
    en_us: Dawarich is a Ruby on Rails-based application with Redis and PostgreSQL integration for managing and processing tasks with Sidekiq.
  developer: Freikin
  icon: https://your-icon-url.com/icon.png
  screenshot_link:
    - https://your-screenshot-url.com/screenshot-1.png
    - https://your-screenshot-url.com/screenshot-2.png
  tagline:
    en_us: A Rails-based task management app using Sidekiq.
  thumbnail: https://your-thumbnail-url.com/thumbnail.png
  index: /
  port_map: "3000"